apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-0001
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/halilagin/LLMs-on-kubernetes.git
    targetRevision: main
    path: llm-0001/llm/yamls
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
