apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
  namespace: llm-0001
    #annotations:
    #argocd.argoproj.io/hook: Sync
    #argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    #argocd.argoproj.io/sync-wave: "2"
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: llm-0001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          #image: postgres
          image: ankane/pgvector
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret-credentials
            - configMapRef:
                name: llm-0001
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
