apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: svc-llm-0001-serve
  namespace: llm-0001
  labels:
    app: llm-0001-serve
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 8000
  # Pod to route service traffic  
  selector:
    app: llm-0001-serve

