apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-llm-fine-tune
  namespace: llm-0001
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: llm-0001-fine-tune
  namespace: llm-0001
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  containers:
    - name: llm-0001-fine-tune
      #image: postgres
      image: halilagin/llm-runner:0.0.1
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: llm-0001
      env:
        - name: WORK_DIR
          value: /opt/llm-fine-tune-storage
        - name: RAYDOCS_ROOT
          value: /opt/llm-fine-tune-storage/raydocs
      volumeMounts:
        - mountPath: /opt/llm-fine-tune-storage
          name: v-llm-fine-tune
      command:
        - bash
        - -c
        - |
          chmod -R 777 $WORK_DIR
          #download scraped content
          rm -rf $RAYDOCS_ROOT && mkdir -p $RAYDOCS_ROOT
          wget --quiet https://github.com/meddash-cloud/meddash-public-datasets/raw/main/archives/docs.ray.io.tar.gz -P $RAYDOCS_ROOT
          cd $RAYDOCS_ROOT && tar xzf docs.ray.io.tar.gz && rm docs.ray.io.tar.gz

          #run fine tuning
          cd /opt/llm-fine-tune-storage 
          git clone $REMOTE_GIT_REPO 
          cd LLMs-on-kubernetes 
          ray start --head --num-cpus=$NUM_CPUS --num-gpus=$NUM_GPUS 
          cd llms/llm-0001/llm_agent
          python3 main.py >/tmp/finetune.log 2>&1
          while true; do sleep 10; done;
  volumes:
    - name: v-llm-fine-tune
      persistentVolumeClaim:
        claimName: pvc-llm-fine-tune
