apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-0001
  namespace: argocd
spec:
  destination:
    namespace: llm-0001
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/halilagin/LLMs-on-kubernetes.git
    targetRevision: main
    path: llms/llm-0001/yamls
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
