apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: postgresdb
  namespace: llm-0001
  labels:
    app: postgresdb
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 5432
  # Pod to route service traffic  
  selector:
    app: postgresdb

